dubbo:
  registry:
    address: zookeeper://192.168.91.131:2181
  protocol:
    port: -1
  application:
    name: studnet
  consumer:
    check: false
spring:
  datasource:
    url: jdbc:mysql:///db_stu?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
